/**
 * collect-slots.mjs — turn a live slot-tree snapshot into the seat directory.
 *
 * The seat directory is the backbone of the layout spec: it answers "where may
 * my UI live, and what does that seat cost me?". The data comes from the
 * harness's own inspection surface (`cordis_inspect_query` → client `Slots` →
 * `listSubTree`), captured to `data/raw/slot-tree-<date>.json`.
 *
 * A snapshot is used rather than a live call because the inspection surface is
 * an agent tool, not a plugin API — a plugin cannot ask it anything. Refreshing
 * the directory means re-running the query and dropping the new file here.
 *
 * Usage: node scripts/collect-slots.mjs [snapshot.json]
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const RAW = join(ROOT, 'data', 'raw')

const explicit = process.argv[2]
const file = explicit ?? (() => {
  if (!existsSync(RAW)) return null
  const candidates = readdirSync(RAW).filter(f => f.startsWith('slot-tree-') && f.endsWith('.json')).sort()
  return candidates.length === 0 ? null : join(RAW, candidates[candidates.length - 1])
})()

if (file === null || !existsSync(file)) {
  console.error('no slot snapshot found — pass one explicitly or drop data/raw/slot-tree-<date>.json')
  process.exit(1)
}

const raw = JSON.parse(readFileSync(file, 'utf8'))
const trees = raw?.data?.trees
if (!Array.isArray(trees)) {
  console.error('snapshot does not contain data.trees — is this really a Slots listSubTree result?')
  process.exit(2)
}

/** Every seat, flattened, in tree order. */
const seats = []

/**
 * Walk one node.
 * @param node - a slot or factory node.
 * @param parent - the parent seat name, or null at a root.
 * @param depth - nesting depth.
 */
function walk(node, parent, depth) {
  if (node.type === 'factory') {
    for (const child of node.children ?? []) walk(child, node.name, depth)
    return
  }
  seats.push({
    name: node.name,
    parent,
    depth,
    kind: node.kind,
    scope: node.scope,
    purpose: (node.purpose ?? '').replace(/\s+/gu, ' ').trim(),
    replaceRisk: node.replaceRisk ?? 'none',
    registration: (node.registration ?? []).map(r => ({ name: r.name, type: r.type, required: r.required === true })),
    keyDomain: node.keyDomain ?? null,
    allowedKeys: node.allowedKeys ?? null,
    childCount: (node.children ?? []).length,
  })
  for (const child of node.children ?? []) walk(child, node.name, depth + 1)
}

for (const tree of trees) walk(tree, null, 0)

const byRisk = {}
const byKind = {}
const byScope = {}
for (const seat of seats) {
  byRisk[seat.replaceRisk] = (byRisk[seat.replaceRisk] ?? 0) + 1
  byKind[seat.kind] = (byKind[seat.kind] ?? 0) + 1
  byScope[seat.scope] = (byScope[seat.scope] ?? 0) + 1
}

const doc = {
  $comment: 'Generated by scripts/collect-slots.mjs from a live harness slot-tree snapshot. Purpose text is the harness\'s own seat description, verbatim.',
  source: file.replace(/\\/gu, '/').replace(`${ROOT.replace(/\\/gu, '/')}/`, ''),
  generatedAt: new Date().toISOString(),
  counts: { seats: seats.length, byRisk, byKind, byScope },
  seats,
}

writeFileSync(join(ROOT, 'data', 'slots.json'), `${JSON.stringify(doc, null, 4)}\n`, 'utf8')

console.log(`seats: ${seats.length}`)
console.log(`  kind: ${Object.entries(byKind).map(([k, v]) => `${k}=${v}`).join(' ')}`)
console.log(`  scope: ${Object.entries(byScope).map(([k, v]) => `${k}=${v}`).join(' ')}`)
console.log(`  replaceRisk: ${Object.entries(byRisk).map(([k, v]) => `${k}=${v}`).join(' ')}`)
