/**
 * gen-index.mjs — build `index.json`, the package's declared entry point.
 *
 * `package.json` advertises `exports: { ".": "./index.json" }`, so that file has
 * to exist and has to be current: a design resource whose front door is a 404 is
 * worse than one that admits it has no front door. What belongs in it is the
 * inventory — where the spec, the guides, the components, the rules and the
 * collected data are — not the content itself, which is far too large to inline
 * and is already addressable by path.
 *
 * Inputs : spec/, guides/, components/index.json, components/origins.json,
 *          rules/rules.json, data/*.json
 * Output : index.json
 *
 * Usage: node scripts/gen-index.mjs [--check]
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import { ROOT, parseFrontmatter, readText } from './lib/i18n.mjs'

const OUT = join(ROOT, 'index.json')

/** Read a JSON file, or a fallback. */
function readJson(rel, fallback) {
  const p = join(ROOT, rel)
  if (!existsSync(p)) return fallback
  return JSON.parse(readFileSync(p, 'utf8'))
}

/** The `# heading` of a document, without its filing number. */
function titleOf(md) {
  const body = parseFrontmatter(md).body
  const m = /^#\s+(.+)$/mu.exec(body)
  return m === null ? '' : m[1].trim().replace(/^\d+\s*/u, '')
}

const specDir = join(ROOT, 'spec')
const spec = existsSync(specDir)
  ? readdirSync(specDir).filter(f => f.endsWith('.md')).sort().map(f => {
      const id = basename(f, '.md')
      const zh = readText(`spec/${f}`)
      const en = readText(`spec/en/${f}`)
      return {
        id,
        file: `spec/${f}`,
        fileEn: en === '' ? null : `spec/en/${f}`,
        title: titleOf(zh),
        titleEn: en === '' ? null : titleOf(en),
      }
    })
  : []

const guideDir = join(ROOT, 'guides')
const guides = existsSync(guideDir)
  ? readdirSync(guideDir).filter(f => f.endsWith('.md')).sort().map(f => {
      const id = basename(f, '.md')
      const zh = readText(`guides/${f}`)
      const en = readText(`guides/en/${f}`)
      return {
        id,
        file: `guides/${f}`,
        fileEn: en === '' ? null : `guides/en/${f}`,
        title: titleOf(zh),
        titleEn: en === '' ? null : titleOf(en),
      }
    })
  : []

const manifest = readJson('components/index.json', { components: [] })
const origins = readJson('components/origins.json', { official: [], proposed: [] })
const official = new Set(origins.official ?? [])
const components = (manifest.components ?? []).map(c => ({
  id: c.id,
  name: c.name,
  category: c.category,
  path: c.path,
  origin: official.has(c.id) ? 'official' : 'proposed',
  readme: existsSync(join(ROOT, c.path, 'README.md')) ? `${c.path}README.md` : null,
  readmeEn: existsSync(join(ROOT, c.path, 'README.en.md')) ? `${c.path}README.en.md` : null,
  spec: existsSync(join(ROOT, c.path, 'SPEC.md')) ? `${c.path}SPEC.md` : null,
  specEn: existsSync(join(ROOT, c.path, 'SPEC.en.md')) ? `${c.path}SPEC.en.md` : null,
  demo: existsSync(join(ROOT, c.path, 'demo.html')) ? `${c.path}demo.html` : null,
}))

const rules = readJson('rules/rules.json', null)
const icons = readJson('data/icons.json', { icons: [] })
const slots = readJson('data/slots.json', { seats: [] })
const tokens = readJson('data/tokens.json', { palette: {}, light: {}, dark: {} })

const translated = list => list.filter(d => d.fileEn !== null).length

const index = {
  $comment: 'Generated by scripts/gen-index.mjs — do not hand-edit. This is the package entry point advertised by package.json exports: an inventory of where each resource lives, with the English counterpart of every document that has one.',
  name: 'dsh-design-resources',
  version: readJson('package.json', {}).version ?? null,
  generatedAt: new Date().toISOString(),
  site: 'website/index.html',
  languages: {
    authored: 'zh',
    translations: 'en',
    coverage: {
      spec: `${translated(spec)}/${spec.length}`,
      guides: `${translated(guides)}/${guides.length}`,
      components: `${components.filter(c => c.readmeEn !== null).length}/${components.length}`,
    },
    contract: 'docs/I18N.md',
  },
  spec,
  guides,
  components: { count: components.length, items: components },
  rules: rules === null ? null : { file: 'rules/rules.json', csv: 'rules/rules.csv', count: (rules.rules ?? []).length },
  data: {
    icons: { count: (icons.icons ?? []).length, file: 'data/icons.json', directory: 'icons/' },
    seats: { count: (slots.seats ?? []).length, file: 'data/slots.json' },
    tokens: {
      file: 'data/tokens.json',
      palette: Object.keys(tokens.palette ?? {}).length,
      lightAliases: Object.keys(tokens.light ?? {}).length,
      darkAliases: Object.keys(tokens.dark ?? {}).length,
    },
  },
}

const next = `${JSON.stringify(index, null, 4)}\n`
if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
  const strip = s => s.replace(/"generatedAt": "[^"]*"/u, '"generatedAt": "X"')
  if (strip(current) !== strip(next)) {
    console.error('index.json is stale — run: node scripts/gen-index.mjs')
    process.exit(1)
  }
  console.log('index.json is up to date')
  process.exit(0)
}

writeFileSync(OUT, next, 'utf8')
console.log(`index.json: spec=${spec.length} guides=${guides.length} components=${components.length}`)
