/**
 * gen-rules.mjs — compile the pre-submission checklist into machine-readable rules.
 *
 * `spec/70-checklist.md` is the human-facing checklist; this turns its tables
 * into `rules/rules.json`, which is what a CI gate or the compatibility auditor
 * consumes. Keeping one source of truth matters: a rule that exists in prose but
 * not here is a rule nobody enforces, and vice versa.
 *
 * Usage: node scripts/gen-rules.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'spec', '70-checklist.md')

if (!existsSync(SRC)) {
  console.error('spec/70-checklist.md is missing — the rule set is compiled from it')
  process.exit(1)
}

const md = readFileSync(SRC, 'utf8')

/** Machine-readable detection tiers. */
const DETECTION = {
  '自动': 'auto',
  '半自动': 'semi',
}

/**
 * Map the checklist's prose detection column onto a tier.
 * @param raw - the column text.
 * @returns { tier, note }.
 */
function detectionOf(raw) {
  const text = raw.trim()
  for (const [key, tier] of Object.entries(DETECTION)) {
    if (text.startsWith(key)) return { tier, note: text === key ? '' : text }
  }
  return { tier: 'manual', note: text }
}

const rules = []
let level = null

for (const line of md.split(/\r?\n/u)) {
  if (/^##\s*A\./u.test(line)) { level = 'required'; continue }
  if (/^##\s*B\./u.test(line)) { level = 'recommended'; continue }
  if (/^##\s*C\./u.test(line)) { level = null; continue }
  if (level === null) continue

  const cells = line.split('|').map(c => c.trim())
  // | id | criterion | clauses | detection |  → ['', id, criterion, clauses, detection, '']
  if (cells.length < 6) continue
  const [, id, criterion, clauses, detection] = cells
  if (!/^[AB]\d{2}$/u.test(id)) continue

  const { tier, note } = detectionOf(detection)
  rules.push({
    id,
    level,
    criterion,
    clauses: clauses.split('/').map(c => c.trim()).filter(Boolean),
    detection: { tier, note },
  })
}

if (rules.length === 0) {
  console.error('parsed zero rules — the checklist table format changed; fix the parser instead of shipping an empty set')
  process.exit(2)
}

const byTier = {}
const byLevel = {}
for (const rule of rules) {
  byTier[rule.detection.tier] = (byTier[rule.detection.tier] ?? 0) + 1
  byLevel[rule.level] = (byLevel[rule.level] ?? 0) + 1
}

const doc = {
  $comment: 'Generated by scripts/gen-rules.mjs from spec/70-checklist.md. Do not hand-edit; edit the checklist and rebuild.',
  source: 'spec/70-checklist.md',
  generatedAt: new Date().toISOString(),
  counts: { total: rules.length, byLevel, byDetection: byTier },
  legend: {
    level: { required: '必选：任一条为否即不得提交', recommended: '推荐：为否需在 README 写明理由（动效组在推荐里：官方没有公开时长与曲线数值）' },
    detection: { auto: '可由脚本对源码／构建产物／渲染结果判定', semi: '脚本给出候选，需人确认', manual: '无法自动化' },
  },
  rules,
}

mkdirSync(join(ROOT, 'rules'), { recursive: true })
writeFileSync(join(ROOT, 'rules', 'rules.json'), `${JSON.stringify(doc, null, 4)}\n`, 'utf8')

/* A flat CSV so the rules can be opened in a spreadsheet or diffed in review. */
const csv = ['id,level,tier,criterion,clauses', ...rules.map(r =>
  [r.id, r.level, r.detection.tier, `"${r.criterion.replace(/"/gu, '""')}"`, `"${r.clauses.join(' ')}"`].join(','))]
writeFileSync(join(ROOT, 'rules', 'rules.csv'), `${csv.join('\n')}\n`, 'utf8')

console.log(`rules: ${rules.length} (required=${byLevel.required ?? 0} recommended=${byLevel.recommended ?? 0})`)
console.log(`  detection: ${Object.entries(byTier).map(([k, v]) => `${k}=${v}`).join(' ')}`)
console.log('  wrote rules/rules.json + rules/rules.csv')
